---

- name: "Install apt-transport-https to allow packages installation using https"
  apt:
    name: apt-transport-https
    state: present

- name: Add apt signing key for gitlab runner repository
  ansible.builtin.apt_key:
    id: F6403F6544A38863DAA0B6E03F01618A51312F3F
    url: https://packages.gitlab.com/gpg.key
    state: present

- name: Add apt repository for gitlab runner
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/config_file.list?os={{ ansible_distribution }}&dist={{ ansible_distribution_release }}&source=script
    dest: /etc/apt/sources.list.d/runner_gitlab-runner.list
    mode: '0644'
